# Generated by Django 2.2.8 on 2020-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_class', models.CharField(choices=[('PR 1', 'PRIMARY 1'), ('PR 2', 'PRIMARY 2'), ('PR 3', 'PRIMARY 3'), ('PR 4', 'PRIMARY 4'), ('PR 5', 'PRIMARY 5'), ('PR 6', 'PRIMARY 6')], default='PR 1', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
    ]
