# Generated by Django 2.2.8 on 2020-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ManyToManyField(to='classes.Class'),
        ),
    ]
