# Generated by Django 2.2.8 on 2020-08-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_remove_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_id',
            field=models.ManyToManyField(null=True, to='subjects.Subject'),
        ),
    ]
