# Generated by Django 2.2.8 on 2020-08-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20200820_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_id',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
    ]
