# Generated by Django 2.2.8 on 2020-08-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='courses_id',
            new_name='subjectcourse',
        ),
    ]
