# Generated by Django 2.2.8 on 2020-08-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.DecimalField(decimal_places=1, default=1, max_digits=8)),
                ('Exam', models.DecimalField(decimal_places=1, default=10, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=20.9, max_digits=8)),
            ],
        ),
    ]
