# Generated by Django 2.2.8 on 2020-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_studentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='student_name',
            field=models.CharField(default='justin', max_length=255),
        ),
    ]
