# Generated by Django 2.2.8 on 2020-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_class', models.CharField(choices=[('JSS1', 'JSS 1'), ('JSS2', 'JSS 2'), ('JSS3', 'JSS 3'), ('SSS1', 'SSS 1'), ('SSS2', 'SSS 2'), ('SSS3', 'SSS 3')], default='JSS1', max_length=255)),
            ],
        ),
    ]
