# Generated by Django 2.2.8 on 2020-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_class',
            field=models.CharField(default='JSS1', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='upload_question',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
