# Generated by Django 2.2.8 on 2020-08-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20200830_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='upload_question',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
