# Generated by Django 2.2.8 on 2020-08-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20200830_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_class',
        ),
    ]
