# Generated by Django 2.2.8 on 2020-08-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annoucement',
            old_name='Annoucements_description',
            new_name='annoucement_description',
        ),
        migrations.RenameField(
            model_name='annoucement',
            old_name='annoucements_title',
            new_name='annoucement_title',
        ),
    ]
