# Generated by Django 2.2.8 on 2020-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_assignmentupload_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentupload',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
    ]
