# Generated by Django 2.2.8 on 2020-08-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primaryfive',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('MUSIC', 'MUSIC')], default='MUSIC', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primaryfour',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('CULTURALARTS', 'CULTURALARTS')], default=('MATHS',), max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primaryone',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('BASIC-SCIENCE', 'BASIC-SCIENCE')], default=('MATHS',), max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primarysix',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('SOCIAL-STUDIES', 'SOCIAL-STUDIES')], default='SOCIAL-STUDIES', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primarythree',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('BASIC-CULTURAL', 'BASIC-CULTURAL')], default=('MATHS',), max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_primarytwo',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('ENGLISH', 'ENGLISH'), ('BASIC-REASONING', 'BASIC-REASONING')], default=('MATHS',), max_length=10),
        ),
    ]
