# Generated by Django 2.2.8 on 2020-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200820_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_primaryfive',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_primaryfour',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_primaryone',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_primarysix',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_primarythree',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_primarytwo',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
