# Generated by Django 2.2.8 on 2020-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=45)),
                ('dept_head', models.CharField(max_length=45)),
                ('teacher_id', models.ManyToManyField(to='teachers.Teacher')),
            ],
        ),
    ]
